server:
  port: 5858
custom:
  db:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/smbms?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      driver: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    strategy:
      mapper-scan-enable: true
      package-scans: com.custom.test, com.custom.aaa
      sql-out-printing: true

