server:
  port: 2021
  servlet:
    context-path: /myTask


  # 数据库连接配置
custom:
  db:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/custom_db?characterEncoding=utf-8&allowMultiQueries=true&autoreconnect=true&serverTimezone=UTC
      username: root
      password: 123456
    config:
      sql-query-after: com.custom.taskmanager.config.MySqlQueryAfter
      sql-interceptor: com.custom.taskmanager.config.MySqlExecuteBefore
      strategy:
        underline-to-camel: true
      table-name-prefix: cm
      table-name-strategy: default


